version: '3.1'
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    restart: unless-stopped
#    environment:
#      - CHOKIDAR_USEPOLLING=true // for hot-reloading

