name: razoo-store

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped
    cpus: 0.25
    mem_limit: 256m
    shm_size: 128m

  backend:
    image: ghcr.io/uch2ha/razoo-store/backend:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=60 -XX:InitialRAMPercentage=20
    restart: unless-stopped
    cpus: 0.25
    mem_limit: 768m

  frontend:
    image: ghcr.io/uch2ha/razoo-store/frontend:latest
    ports:
      - '5173:80'
    depends_on:
      - backend
    restart: unless-stopped
    cpus: 0.15
    mem_limit: 128m