version: '3.1'
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: eShopDB
    ports:
      - "2345:5432"
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eShopDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=2B4B6250655367566B5970337336763979244226452948404D635166546A576
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    restart: unless-stopped
    environment:
      - VITE_GOOGLE_CLIENT_ID=465239718285-7jlb2sld852tlau1o5hbqgl8f9tevko9.apps.googleusercontent.com
      - VITE_BASE_URL=http://localhost:8080
      - VITE_API_VERSION=/api/v1
#      - CHOKIDAR_USEPOLLING=true // for hot-reloading


#networks:
#  db:
#    driver: bridge
#volumes:
#  db: