spring:
  datasource:
    url: jdbc:postgresql://localhost:${PSQL_PORT}/${PSQL_DB_NAME}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: false
    defer-datasource-initialization: true

  devtools:
    remote:
      secret: mysecret
  sql:
    init:
      mode: always
  config:
    import: optional:file:./backend/.env[.properties]

#logging:
#  level:
#    org.springframework.data: debug

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##spring.datasource.hikari.connectionTimeout=20000
##spring.datasource.hikari.maximumPoolSize=5
##
##spring.jpa.hibernate.properties.hibernate.temp.use_jdbc_metadata_defaults=false
